### ISSUE TITLE
Failed to resolve: com.github.aliab:Persian-Date-Picker-Dialog:1.8.0

### ISSUE THREAD

**Issue by hysapp** [aliab/Persian-Date-Picker-Dialog#100]
Cannot sync `Gradle` with dependency:
`implementation 'com.github.aliab:Persian-Date-Picker-Dialog:1.8.0'`

`Failed to resolve: com.github.aliab:Persian-Date-Picker-Dialog:1.8.0`

It seems to be related to `JCenter` problems.

**Comment by aliab** [comment]
add maven { url 'https://jitpack.io' } to your allProject, repositories
