### ISSUE TITLE
افزودن قابلیت

### ISSUE THREAD

**Issue by aminsato** [aliab/Persian-Date-Picker-Dialog#106]
با تشکر از زحماتتون بابت این تقویم

لطفا یک تابع فقط برای خروجی unix بگذارید 
 این تابع getTimestamp  هست ولی اپوک زمانی برمیگردونه
به عبارت دیگه برای گرفتن  خروجی unix باید مقدار خروجی تابع getTimestamp  را بر 1000 تقسیم کرد
و یک تابع برای setdate  برای که ورودی unix بگیره

 لطفا یک قابلیت بذارید که تاریخ از طریق  کیبورد در picker ادیت نشه  چون وقتی روی picker کلیک میکنم کیبورد باز میشه 
به عبارت دیگه یک قابیلت bool  برای view

**Comment by aminsato** [comment]
سلام
میتونم در توسعه این مورد مشارکت کنم؟

**Comment by aliab** [comment]
> سلام میتونم در توسعه این مورد مشارکت کنم؟

حتما. ممنون میشم PR بدید

**Comment by FanitoApp** [comment]
> > سلام میتونم در توسعه این مورد مشارکت کنم؟
> 
> حتما. ممنون میشم PR بدید

نمیتونم PR برنم باید collaborator  باشیم

**Comment by FanitoApp** [comment]
> > سلام میتونم در توسعه این مورد مشارکت کنم؟
> 
> حتما. ممنون میشم PR بدید

لطف میکنید منو collaborator  کنید؟

توی branch dev PR بزنم؟

**Comment by aminsato** [comment]
> > سلام میتونم در توسعه این مورد مشارکت کنم؟
> 
> حتما. ممنون میشم PR بدید

سلام نمیتونم PR بزنم چون collaborator نیستم

توی Branch dev , پول ریکسوت (PR) بزنم؟

**Comment by aliab** [comment]
نیازی به این موضوع نیست.
https://www.dataschool.io/how-to-contribute-on-github/

**Comment by aminsato** [comment]
**I hava Done this . please review this**
#111

**Comment by aliab** [comment]
ممنونم. مرج شد
