### ISSUE TITLE
بسته شدن دیالوگ

### ISSUE THREAD

**Issue by vahidarr** [aliab/Persian-Date-Picker-Dialog#11]
با سلام لطفا خصوصیت دیالوگ خود اندروید ()setCancelable را اضافه کنید. اینجا گفتم چون یه جورایی ایراد هست وقتی بعضی مواقع نیاز هست پنجره بسته نشود

**Comment by aliab** [comment]
این قابلیت تو نسخه جدید اضافه شد٬ ممنونم از پیشنهادتون
