### ISSUE TITLE
"مشکل در "برو به امروز

### ISSUE THREAD

**Issue by hessam71d** [aliab/Persian-Date-Picker-Dialog#21]
تو 31 مرداد، وقتی میزدم "برو به امروز" میرفت رو 29 مرداد
الان که 1 شهریور هستیم، اون دکمه رو میزنم درست عمل میکنه
فکر کنم 30 و 31 رو درست عمل نمیکنه

**Comment by majidghafouri** [comment]
توی 30 شهریور هستیم و هنوز مشکل حل نشده.
دکمه امروز 30 و 31 هر ماهی رو میندازه روی 29 همون ماه.
لطفاً بررسی کنید.

**Comment by hessam71d** [comment]
سلام دوست عزیز خیلی ممنون از اینکه اطلاع دادید.

**Comment by AlirezaNoorali** [comment]
سلام. دوستان لطفا اگر باگی رو برطرف میکنید بنویسید که بدونیم استفاده کنیم یا خیر. چون در اپ من تاریخ اهمیت خیلی زیادی داره و خطا میتونه ضرر مالی زیادی وارد کنه.

**Comment by mjalijani** [comment]
سلام این مشکل هنوز وجود داره برای من امروز 30 خرداد ولی وقتی میزنم امروز میره 29 خرداد

**Comment by adelhoss** [comment]
با سلام 
بزرگواران من هم همین مشکل رو دارم و کاربران اپ ما متاسفانه با برو به امروز اطلاعات زیادی ثبت کردند 
و گفتند که ما متوجه نشدیم که برو به امروز اشتباه کار می کنه
لطفا راه حلی ارائه بدین تا ارائه ی نسخه ی جدید
ممنونم اگر دوستان راه حل فعلی خودشون رو ارائه بدن ممنون

**Comment by aliab** [comment]
ممنونم از گزارشتون. تو نسخه ۱.۵.۰ این مشکل حل شد

**Comment by mjalijani** [comment]
سلام دوباره 
من وقتی نسخه 1.5.0 یا نسخه ی 1.5.1 رو وقتی اضافه میکنم موقع sync شدن این خطا رو میده

> ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:25:5-185:19 to override.

My Gradle:

>  dependencies {
>         classpath "io.chabok.plugin:chabok-services:1.0.0"
>         classpath 'com.android.tools.build:gradle:3.5.3'
>         classpath 'com.google.gms:google-services:4.3.3'
>         classpath 'io.fabric.tools:gradle:1.31.2'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> 
>    implementation 'com.github.aliab:Persian-Date-Picker-Dialog:1.5.1'
>     implementation 'net.cachapa.expandablelayout:expandablelayout:2.9.2'
>     implementation 'com.google.firebase:firebase-messaging:17.1.0'
>     implementation 'com.google.android.gms:play-services-auth:16.0.0'
>     implementation 'com.google.firebase:firebase-analytics:16.0.1'
>     implementation 'com.google.firebase:firebase-core:16.0.1'
>     implementation 'com.google.android.gms:play-services-gcm:15.0.1'
>     implementation 'com.android.installreferrer:installreferrer:1.0'
