### ISSUE TITLE
Bug in getPersianShortDateTime()

### ISSUE THREAD

**Issue by SaeedShadab** [aliab/Persian-Date-Picker-Dialog#24]
Dear Ali,
Hi.
A bug exist in getPersianShortDateTime() method !
when select day (9) For Example : 1397/08/09 this method returned : 1397/08/9
that is wrong.
i think this method has problem 👍 
private String formatToMilitary(int i) {
        return i < 9 ? "0" + i : String.valueOf(i);
    }

**Comment by aminmeshk** [comment]
this works well:
`return String.format("%02d", i);`
