### ISSUE TITLE
مشکل عجیب در تبدیل تاریخ

### ISSUE THREAD

**Issue by abbasalim** [aliab/Persian-Date-Picker-Dialog#26]
سلام. در موردی عجیب وقتی تاریخ ها رو توی روز ۳۰ آخرین ماه 2018 تبدیل به فارسی می کردی نتایج اشتباها این میشد:
![31dec2018](https://user-images.githubusercontent.com/2588914/50570831-b7775600-0daf-11e9-8b9e-8aa1bb567ef7.png)
اما در اولین روز اولین ماه 2019 این میشه 
![1jan-2019](https://user-images.githubusercontent.com/2588914/50570833-c3631800-0daf-11e9-9448-48a8265d7c7f.png)

**Comment by aliab** [comment]
امکانش هست کد با من به اشتراک بذارید؟

**Comment by abbasalim** [comment]
سلام. خیلی وقت از این مشکل میگذره وولی زمان و تاریخ رو بهتون دادم میتونید تست کنید من چون اپ حسابداری بود مجبور شدم از کتابخونه دیگه استفاده کنم

**Comment by aliab** [comment]
نتیجه بازگشتی از کتابخونه رو تبدیل به تاریخ میلادی میکردید؟ یا تاریخ اولیه به اشتباهی تنظیم می‌شده؟

**Comment by abbasalim** [comment]
ببینید در مثال بالا من نتیجه  میلادی بازگشتی از دیت پیکر رو دردیتابیس ذخیره میکردم
اون درست مشکلی نیست.
مشکل اینجاست که من وقتی با کتابخونه شما تاریخ های میلادی رو به شمسی تبدیل میکردم در یه بازه های زمانی خاصی (فکر میکنم بیشتر آخر سالهای میلادی) تاریخ رو اشتباه تبدیل میکرد و بعد از گذشت یک روز (شایدم چندساعت) مجدد تاریخ ها درست تبدیل میشدن

///////////////////
یعنی مبدل تاریخ مشکلی داره که شاید مثلا سال کبیسه میلادی رو اشتباه محاسبه میکنه که نتیجه این میشه یا ساعتش عقب/جلویی داره یا نمیدونم.
/////
در کل عیب از مبدل هست نه دیت پیکر

**Comment by aliab** [comment]
@abbasalim پس احتمالا مشکل از کتابخونه PersianDate هست که باید حل بشه٬ ممنونم.
این مورد میذارم تو لیست مشکلات که باید حل بشه
