### ISSUE TITLE
حداکثر تاریخ

### ISSUE THREAD

**Issue by MasoudMHS** [aliab/Persian-Date-Picker-Dialog#32]
چطور میشه حداکثر ماه و روز رو مشخص کرد؟؟

**Comment by iman2420** [comment]
واقعا نمیشه از ایرانی انتظار داشت یک کار رو بصورت کامل و بی عیب و نقص انجام بده ؟

**Comment by golnarSheikhBahaie** [comment]
> چطور میشه حداکثر ماه و روز رو مشخص کرد؟؟

............................
من خودم یک متد نوشتم که تاریخ روز سیستم رو میگیره و با تاریخ انتخاب شده مقایسه میکنه .. اگر بزرگ تر بود 
 شروطم اجرا  نمیشه

**Comment by aliab** [comment]
این قابلیت در نسخه بعدی اضافه میکنم
