### ISSUE TITLE
RTL/LTR and AndroidX issues

### ISSUE THREAD

**Issue by sobimor** [aliab/Persian-Date-Picker-Dialog#33]
Dialog layout direction is wrong when local is "fa" (Year at right side, Day at left side) and in next release please migrate it to AndroidX.

**Comment by sobimor** [comment]
Android version: 9

**Comment by sobimor** [comment]
For solving RTL/LTR in "fa" local :
1. setLocal to "en" before initialize
2. setLocal to "fa" in onDateSelected  and onDismissed

**Comment by aliab** [comment]
Thank you for your report. this issue fixed in version 1.5.0

**Comment by HJaliliani** [comment]
This is a bug in androidx  appcompat 1.1.0, I fixed it & create a pull request @aliab @sobimor

**Comment by aliab** [comment]
@HJaliliani it was just an issue with RTL in a linearlayout. because developer set 'fa' local, every layout change to RTL mode and that was an issue.
