### ISSUE TITLE
why ERROR: Failed to resolve: com.github.aliab:Persian-Date-Picker-Dialog:1.4?

### ISSUE THREAD

**Issue by daavarr** [aliab/Persian-Date-Picker-Dialog#35]
i added the JitPack repository successfully, but when i implement (implementation 'com.github.aliab:Persian-Date-Picker-Dialog:1.4')  this error shown to me :
ERROR: Failed to resolve: com.github.aliab:Persian-Date-Picker-Dialog:1.4
Show in Project Structure dialog
Affected Modules: app

thanks

**Comment by golnarSheikhBahaie** [comment]
i have same problem but my problem was for  (app-compact version )
.. now i set this in my gradle :
 implementation 'com.android.support:appcompat-v7:28.0.0'
 implementation 'com.android.support:support-v4:28.0.0'
and this is my persian datepicker dependency 
 implementation 'com.github.aliab:Persian-Date-Picker-Dialog:1.4'

**Comment by daavarr** [comment]
thanks its working

**Comment by aliab** [comment]
@golnarSheikhBahaie @daavarr version 1.5.0 migrated to AndroidX, thanks for your report.
