### ISSUE TITLE
تنظیم محدودیت روی روز

### ISSUE THREAD

**Issue by iman2420** [aliab/Persian-Date-Picker-Dialog#37]
سلام ممنون بابت لایبری خوبتون.
 میخوام محدودیت بگذارم روی روز های دیالوگ، بصورتی که از امروز تا 14 روز آینده بیشتر قابل انتخاب نباشه، مشکل اینجاست اگر آخر ماه باشی باید آیتم ماه رو هم هندل کنی.
ممنون میشم در این خصوص راهنمایی کنید.

**Comment by aliab** [comment]
ممنونم. این مورد فعلا تو کتابخونه نیست ولی تو نسخه بعد اضافه میکنم
