### ISSUE TITLE
conflict with material component

### ISSUE THREAD

**Issue by Azinnilchi** [aliab/Persian-Date-Picker-Dialog#39]
hi, first of all, thank you for your helpful library. I can use it in a simple project. the problem is that when I have a material component, my Gradle will sync but I can't run it. I use androidX and the material component which I use is :

`implementation 'com.google.android.material:material:1.2.0-alpha01'`

and I get the following error : 
`Could not find fragment.jar (androidx.fragment:fragment:1.1.0).
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.jar`

how can I fix this issue?!

**Comment by aliab** [comment]
it seems that you can't access the fragment-1.1.0.jar file at the google repository. check your internet connection or clean the Gradle cache. maybe this things can help you.
