### ISSUE TITLE
azar return value is not correct

### ISSUE THREAD

**Issue by Ehsan-Yz** [aliab/Persian-Date-Picker-Dialog#43]
in PersianCalendar.java :
---------------------------------------------
private String formatToMilitary(int i) {
	return (i < 9) ? "0" + i : String.valueOf(i);
}

this line :
return (i < 9) ? "0" + i : String.valueOf(i);

change to :
return (i <= 9) ? "0" + i : String.valueOf(i);

**Comment by aliab** [comment]
Thank you for your report, Please update to 1.6.1
