### ISSUE TITLE
initdate not working

### ISSUE THREAD

**Issue by hessam71d** [aliab/Persian-Date-Picker-Dialog#44]
سلام ضمن تشکر از توسعه دهنده این لایبرری مفید و کاربردی میخواستم یه مشکلی رو بگم.
مشکل اینجاست که وقتی یه تاریخ ست میکنم، بعدش که دیالوگ رو نمایش میدم به جای اینکه **اون روز** رو نشون بده همیشه **روز فعلی** رو بالا میاره و نمایش میده

مثلا به این صورت تاریخ 1398/9/5 رو ست میکنم:

final PersianCalendar initDate = new PersianCalendar();             
initDate.setPersianDate(1398,9,5);

  final PersianDatePickerDialog picker = new PersianDatePickerDialog(ActivityPerson.this)
                        .setPositiveButtonString("ok")
                        .setNegativeButton("dismiss")
                        .setTodayButton("today")
                        .setTodayButtonVisible(true)
                        .setInitDate(initDate)
                        .setMinYear(1300)
                        .setActionTextColor(getResources().getColor(R.color.colorPrimaryDark))
                        .setListener(new Listener() {...});

picker.show();

من تا نسخه ی زیر یعنی:
    implementation 'com.github.hamsaadev:Persian-Date-Picker-Dialog:V1.2'
این مشکلی که گفتم رو نداشتم ولی بعد از اون نسخه همشون این مشکل رو دارن

سپاس از توجه شما.

**Comment by aliab** [comment]
من تست کردم مشکلی ندیدم٬ رو دستگاه خاصی به مشکل میخورید؟

**Comment by hessam71d** [comment]
عجیبه! والا من روی سامسونگ اس 9 اندروید 9 و روی ایمولاتور اندروید 10 و ایمولاتور اندروید 4.2 تست کردم
همشون همین مشکل رو داشتن

الان این خط رو:

.setInitDate(initDate)

تبدیل کردم به:

.setInitDate(initDate,true)

و کاملا **درست شد** هوراااااا!!!!

یه آپشن فورس داشت باید فعالش میکردم ظاهرا
