### ISSUE TITLE
ERROR: Failed to resolve: coordinatorlayout

### ISSUE THREAD

**Issue by salario07** [aliab/Persian-Date-Picker-Dialog#45]
بعد از آپدیت به ورژن 1.5.1 از  1.5.0 گریدل بیلد نمیشود و این ارور رو میدهد
ERROR: Failed to resolve: coordinatorlayout
Affected Modules: app

**Comment by aliab** [comment]
check your internet connection

**Comment by salario07** [comment]
you're right.my problem solved next time i tried!
