### ISSUE TITLE
Wrong day on day wheel 

### ISSUE THREAD

**Issue by javadghane** [aliab/Persian-Date-Picker-Dialog#46]
Hi, thanks for great library. if i use today button the day wheel show today as well.  but when the datepicker start the current day wheel show one day before actual day. (tested at 01:57 am) 
the day on wheel is one day before but actual header is ok. 
again thanks for making this lib.

**Comment by aliab** [comment]
Thanks for your report. this issue has been fixed now. 
update to version 1.5.2
