### ISSUE TITLE
اضافه نشدن پکیج

### ISSUE THREAD

**Issue by mj-android-mj** [aliab/Persian-Date-Picker-Dialog#53]
سلام من هر کاری کردم نتونستم پکیج رو از طریق گردل به برنامه اضافه کنم

**Comment by danaShayan** [comment]
منم همینطور

**Comment by aliab** [comment]
لطفا مراحل توضیح داده شده رو به دقت انجام بدید و از اتصال وی پی ان هم مطمئن بشید
