### ISSUE TITLE
سال 1399 به بعد رد تقویم نیست

### ISSUE THREAD

**Issue by tahlilgar** [aliab/Persian-Date-Picker-Dialog#55]
سال 99 ببعد به تقویم افزوده خواهد شد؟ چون ما میخوایم اپلیکیشن رو در شروع سال جدید ارائه کنیم اگر افزوده نخواهد شددنبال ویجت دیگری باشیم لطفا پاسخ بدین ممنون

**Comment by emadmahouti** [comment]
`.setMaxYear(1450)`
