### ISSUE TITLE
ارور تگ در متد OnDateSelected

### ISSUE THREAD

**Issue by AbrahamEH** [aliab/Persian-Date-Picker-Dialog#57]
سلام وقت بخیر بنده تازه شروع به برنامه نویسی کردم و تازه کارم و از کتاب خانه شما که استفاده میکنم میخوام اون رو به صورت یک متد بکنم و با زده شدن دکمه تاریخ اون رو فراخانی کنم اما TAG ها ارور میدن
![Uploading Screenshot (58).png…]()

**Comment by aliab** [comment]
لطف میکنید خطا رو بفرستید؟

**Comment by AbrahamEH** [comment]
حل شد با
import 
کردن کلاس ها
🖤
