### ISSUE TITLE
ERROR: Failed to resolve: com.github.aliab:Persian-Date-Picker-Dialog:1.5.2

### ISSUE THREAD

**Issue by saminh97** [aliab/Persian-Date-Picker-Dialog#59]
سلام خسته نباشید. من قبلا از این کد استفاده کرده بودم و به مشکلی برنخورم موقه اضافه کردن دپندنسی ولی امروز واسه یه پروژه جدید این ارورو داره بهم میده. شما میدونید ممکنه مشکل از کجا باشه؟

**Comment by aliab** [comment]
احتمالا مشکل از VPN یا اینترنت باشه
