### ISSUE TITLE
مشکل انتخاب تاریخ اشتباه  - بسیار جدی

### ISSUE THREAD

**Issue by smartmob98** [aliab/Persian-Date-Picker-Dialog#61]
سلام خسته نباشین 

وقتی میخوایم مثلا تاریخ  
1399/08/14
انتخاب کنیم 

خود به خود تاریخ 

1399/09/14

رو بر میداره 

یا مثلا از تایخ امروز بخوایم یک روز بعد رو انتخاب کنیم ،  یک ماه میره جلو تر

این مشکل از مهر ماه  سال 99 مشاهده شده

لطفا سریع  تر رفع بفرمایید به مشکل جدی خوردیم

**Comment by hamidrezakhajeh** [comment]
سلام، همچین مشکلی رو منم باهاش روبرو شدم، جالب تر اینکه روی شبیه ساز اوکی هست اما توی گوشی واقعی همچین چیزی اتفاق میوفته و اصلا نمیشه مثلا 14/8/1399 رو انتخاب کرد اتومات میره ماه بعد!

**Comment by yamin8000** [comment]
سلام
من هرچی تست کردم همچین مشکلی پیش نمیاد؟
چطور ممکنه؟

**Comment by hamidrezakhajeh** [comment]
> سلام
> من هرچی تست کردم همچین مشکلی پیش نمیاد؟
> چطور ممکنه؟

سلام برای منم توی شبیه ساز درسته اما توی دستگاه واقعی همچین مشکلی پیش میاد واقعا مورد عجیبیه :))

**Comment by yamin8000** [comment]
> 
> 
> > سلام
> > من هرچی تست کردم همچین مشکلی پیش نمیاد؟
> > چطور ممکنه؟
> 
> سلام برای منم توی شبیه ساز درسته اما توی دستگاه واقعی همچین مشکلی پیش میاد واقعا مورد عجیبیه :))

به نظرت ممکنه به خاطر تایم زون یا لوکیل شبیه سازت باشه؟

**Comment by ARNvoid** [comment]
سلام
موقع انتخاب از تاریخ 1399/11/13 تا تاریخ 1399/12/10 هم مشکل پرش داره اگه میشه بررسی کنید
هم شبیه ساز هم دیوایس واقعی
برای متد 
`persianCalendar.setPersianDate(year, month, day);`
اعداد رو هم لاگ گرفتم قبل از متد درست بود 

```
Before: 1399#11#13
After: 1399/12/11
```

**Comment by yamin8000** [comment]
> 
> 
> سلام
> موقع انتخاب از تاریخ 1399/11/13 تا تاریخ 1399/12/10 هم مشکل پرش داره اگه میشه بررسی کنید
> هم شبیه ساز هم دیوایس واقعی
> برای متد
> `persianCalendar.setPersianDate(year, month, day);`
> اعداد رو هم لاگ گرفتم قبل از متد درست بود
> 
> ```
> Before: 1399#11#13
> After: 1399/12/11
> ```
> 
> @yamin8000

پس اگه اینطوری باشه اون لایبری که برای تقویم استفاده شده مشکل داره
به نظرم اون کلاس های تقویم اش قدیمی هم باشه اگه سورسش نگاه کنی
اکثرا بعد یه مدت برای تاریخ های جدیدتر  محاسبات این کدا اشتباه میشه
کاش از تقویم فارسی
https://github.com/persian-calendar/DroidPersianCalendar
استفاده میشد که به صورت مداوم در حال بروزرسانیه

**Comment by herotux** [comment]
بله این مشکل قطعا برای استفاده از لایبری تقویمش هست منم از این لایبری برای پروژه ای استفاده کردم که با تایم زون به مشکل میخورد و در نهایت با این لایبری تعویض کردم که کارکرد مشابهی داره اما به دقت محاسبه می‌کنه

https://github.com/samanzamani/PersianDate

بنظرم بهتره جایگزین بشه و اگر بشه که عالیه

**Comment by aliab** [comment]
@herotux 
مرسی واسه پیشنهادت. تو اپدیت بعدی این کتابخونه رو جایگزین میکنم

**Comment by herotux** [comment]
> @herotux
> مرسی واسه پیشنهادت. تو اپدیت بعدی این کتابخونه رو جایگزین میکنم

تغییرات رو انجام دادم و پول ریکوئست دادم یه بررسی کن ببین داستان چطور میشه

**Comment by aliab** [comment]
به نسخه ۱.۶.۱ به روز رسانی کنید. مشکل حل خواهد شد
