### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by r2g5b5** [aliab/Persian-Date-Picker-Dialog#71]
![device-2021-07-17-161832](https://user-images.githubusercontent.com/16062472/126035937-efa546db-c40f-43ae-bc91-c7781873e82c.png)

چندتا تاریخ دیگه همین مشکل رو داره، درست نشون نمیده

**Comment by aliab** [comment]
Thank you for your report. it is now fixed in version 1.7.1 [#72]
