### ISSUE TITLE
مشکل انتخاب تاریخ

### ISSUE THREAD

**Issue by sourena21** [aliab/Persian-Date-Picker-Dialog#77]
سلام
توی انتخاب تاریخ برای 10 شهریور در سال های 1400 و 1401 و 1402 مشکلی وجود داره به این صورت که وقتی کاربر این تاریخ ها رو تو تقویم انتخاب می کنه و تایید می کنه، تقویم تاریخ 9 مهر رو بهش بر می گردونه.
این اتفاق دقیقا همین امروز که 9 شهریور 1400 هست برای اپ ما افتاده و وقتی کاربرانمون تاریخ فردا رو انتخاب می کنن، تقویم 9مهر رو برمی گردونه.

**Comment by ali-koohi** [comment]
من هم معمولا وقتی این مشکل رو دارم که آخرین روز میلادی باشه ، 9 شهرویر هم 31 آگوست بوده
