### ISSUE TITLE
استفاده از دیت پیکر خارج از دیالوگ

### ISSUE THREAD

**Issue by sourena21** [aliab/Persian-Date-Picker-Dialog#9]
سلام
چه جوری میشه دیت پیکر رو خاج از دیالوگ و توی لایه اصلی ایکس ام ال
 استفاده کرد؟

**Comment by karimi12** [comment]
یه نگاهی به این بنداز 

https://github.com/alibehzadian/PersianDatePicker

**Comment by sourena21** [comment]
از اینم استفاده کرده بودم
حلش کردم
یه کاستوم زدم
شبیه به چیزی که محمد امین درست کرده اما پاپ آپ نشون داده میشه
