### ISSUE TITLE
onDismissed dont work

### ISSUE THREAD

**Issue by HoFa1997** [aliab/Persian-Date-Picker-Dialog#92]
salam man az method onDismissed
estefade mikonam dakhel barname vali kar nmikone  
va debug am kardam aslan vared on method nmishod

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.github.aliab:Persian-Date-Picker-Dialog:1.8.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

**Comment by Hoss3inf** [comment]
has been addressed in #97
